# Generated by Django 4.1.7 on 2023-03-28 16:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staff'},
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='experiment_folder',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='experiment',
            name='experiment_file',
            field=models.CharField(default='', max_length=255, verbose_name='experimental data file path'),
        ),
        migrations.AddField(
            model_name='sample',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='main.sample'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='date_created',
            field=models.DateField(help_text='when was the data created'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiments', to='main.method'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='name',
            field=models.CharField(help_text='free text field', max_length=255),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiments', to='main.project'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiments', to='main.sample'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiments', to='main.staff'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiments', to='main.user'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='affiliation',
            field=models.CharField(blank=True, help_text='if applicable: umbrella organization', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='email',
            field=models.EmailField(help_text='e.g. administration office', max_length=254),
        ),
        migrations.AlterField(
            model_name='institute',
            name='telephone',
            field=models.CharField(help_text='e.g. administration office', max_length=50),
        ),
        migrations.AlterField(
            model_name='method',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='methods', to='main.institute'),
        ),
        migrations.AlterField(
            model_name='method',
            name='method_folder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_folder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='date_created',
            field=models.DateField(help_text='date of creation, rarely: delivery'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='main.institute'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='main.method'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.CharField(help_text='free text field', max_length=255),
        ),
        migrations.AlterField(
            model_name='sample',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='main.project'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_id',
            field=models.CharField(help_text='a unique 20-character identifier for the sample', max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_info',
            field=models.CharField(help_text='link to sample type-specific information', max_length=255, verbose_name='sample information file'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='main.sampletype'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='supplementary_file',
            field=models.CharField(blank=True, help_text='if applicable: datasheet, etc.', max_length=255, null=True, verbose_name='supplementary file path'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='main.user'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=False, help_text='employment status'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='main.institute'),
        ),
    ]
